version: '3.4'

networks:
  OPEN5GS:
    driver: macvlan
    driver_opts:
      parent: bond0.4000
    ipam:
      driver: default
      config:
        - subnet: 192.168.186.0/24

volumes:
  mongo_data:

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      OPEN5GS:
        ipv4_address: 192.168.186.10
    volumes:
      - mongo_data:/data/db

  mongosetup:
    image: mongo
#    restart: no
    depends_on:
      - mongo
    volumes:
      - ./mongoinit:/config
    networks:
      OPEN5GS:
    command: ['/config/init.sh']

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      OPEN5GS:
        ipv4_address: 192.168.186.11

  open5gs_webui:
    image: registry.the-resolvers.net/open5gs/open5gs-webui:latest
    restart: always
    ports:
      - 9999:9999
    environment:
      DB_URI: mongodb://open5gs:open5gs@mongo:27017/open5gs
    depends_on:
      - mongo
      - mongosetup
    networks:
      OPEN5GS:
        ipv4_address: 192.168.186.12

#### DLA ####
  open5gs_hss:
    image: registry.the-resolvers.net/open5gs/open5gs-base
    container_name: open5gs-hss
    restart: unless-stopped
    depends_on:
      - mongo
      - mongosetup
    volumes:
      - ./open5gs-hss:/config
    command: /opt/open5gs/bin/open5gs-hssd -c /config/hss.yaml
    networks:
      OPEN5GS:
        ipv4_address: 192.168.186.20

  open5gs_pcrf:
    image: registry.the-resolvers.net/open5gs/open5gs-base
    container_name: open5gs-pcrf
    restart: unless-stopped
    depends_on:
      - mongo
      - mongosetup
    volumes:
      - ./open5gs-pcrf:/config
    command: /opt/open5gs/bin/open5gs-pcrfd -c /config/pcrf.yaml
    networks:
      OPEN5GS:
        ipv4_address: 192.168.186.25


#### PacketCore ####
  open5gs_mme:
    image: registry.the-resolvers.net/open5gs/open5gs-base
    container_name: open5gs-mme
    restart: unless-stopped
    depends_on:
      - open5gs_hss
    volumes:
      - ./open5gs-mme:/config
    command: /opt/open5gs/bin/open5gs-mmed -c /config/mme.yaml
    networks:
      OPEN5GS:
        ipv4_address: 192.168.186.30

#### SGW ####
  open5gs_sgwc:
    image: registry.the-resolvers.net/open5gs/open5gs-base
    container_name: open5gs-sgwc
    restart: unless-stopped
    depends_on:
      - open5gs_mme
    volumes:
      - ./open5gs-sgwc:/config
    command: /opt/open5gs/bin/open5gs-sgwcd -c /config/sgwc.yaml
    networks:
      OPEN5GS:
        ipv4_address: 192.168.186.40

  open5gs_sgwu:
    image: registry.the-resolvers.net/open5gs/open5gs-base
    container_name: open5gs-sgwu
    restart: unless-stopped
    depends_on:
      - open5gs_sgwc
    volumes:
      - ./open5gs-sgwu:/config
    command: /opt/open5gs/bin/open5gs-sgwud -c /config/sgwu.yaml
    networks:
      OPEN5GS:
        ipv4_address: 192.168.186.41


#### PGW ####
  open5gs_smf:
    image: registry.the-resolvers.net/open5gs/open5gs-base
    container_name: open5gs-smf
    restart: unless-stopped
    depends_on:
      - open5gs_mme
    volumes:
      - ./open5gs-smf:/config
    command: /opt/open5gs/bin/open5gs-smfd -c /config/smf.yaml
    networks:
      OPEN5GS:
        ipv4_address: 192.168.186.50

  open5gs_upf:
    image: registry.the-resolvers.net/open5gs/open5gs-base
    container_name: open5gs-upf
    restart: unless-stopped
    depends_on:
      - open5gs_mme
    volumes:
      - ./open5gs-upf:/config
    command: /opt/open5gs/bin/open5gs-upfd -c /config/upf.yaml
    networks:
      OPEN5GS:
        ipv4_address: 192.168.186.51
    privileged: true
